### PR TITLE
add address information

### LINKED ISSUE #2: Consider adding address information to SE ConsumerLoanApplication
Fields such as:
`firstName`
`lastName`
`address`
`city`
`postalCode`
`careOf`

### PR DESCRIPTION
**Pull request by williamhogman**
This closes #2

### CODE REVIEW

**Comment by williamhogman** [comment]
The address information is tentative and I have no idea how to explain that clearly in the specification.
It would be proper DD for a lender to acquire this information themselves

**Comment by zinob** [comment]
@williamhogman  What are the intended uses for a tentative address?

**Comment by williamhogman** [comment]
Some people need this :(

**Comment by zinob** [comment]
Might i suggest some wording about its primary purpose being for validatin against sensus or fall-back in case the sensus information is out of date?

**Comment by williamhogman** [comment]
The point is to indicate that relying on the address provided might be bad practice

**Pull request merged**
