### PR TITLE
Adds fields to Loan Purpose (Private Unsecure Loans)

### PR DESCRIPTION
**Pull request by 6185541513**
~~The suggestion is to add two more fields to blanco loans in Norway:~~

- ~~HOME_DOWNPAYMENT~~
- ~~DIVORCE_PROCEEDINGS~~

~~_Motivation:_~~
~~The honest motvation is that rickard has added them in frontend and i trust he got them from a valid source? Also, they feel very resonable to me at least.~~

---------------------------------------------------

**UPDATE**
Got info from ceo, these are the required fields for both sweden and norway Private Unsecure Loans:
- REFINANCE
- HOME_REMODELLING
- INVESTMENT
- EDUCATION
- TRAVEL
- CAR
- OTHER

If we were to include all and only these fields, it would mean removing existing fields. Since this specification is outside the scope of only our company, the suggestion is to not remove any fields, but only adding missing ones. 

Therefore, these would be the fields:
**SWEDEN:**
- REFINANCE
- HOME_REMODELLING
- HEALTHCARE_EXPENSES
- DIVORCE_PROCEEDINGS
- HOME_DOWNPAYMENT
- **INVESTMENT [new]**
- EDUCATION
- TRAVEL
- CAR
- OTHER

**NORWAY:**
- REFINANCE
- HOME_REMODELLING
- HEALTHCARE_EXPENSES
- **INVESTMENT [new]**
- EDUCATION
- TRAVEL
- CAR
- OTHER

### CODE REVIEW

**Comment by mantono** [comment]
They do seem reasonable indeed. Maybe he can give him some background on these values?

**Comment by 6185541513** [comment]
> They do seem reasonable indeed. Maybe he can give him some background on these values?

I've asked the managers in slack, where he shold have gotten the info from. Will get back with info as soon as they reply.

**Comment by mantono** [comment]
I am a bit confused now. It seems like `REFINANCE` already exists (it really **should** be present in the specification already).

**Comment by 6185541513** [comment]
> I am a bit confused now. It seems like `REFINANCE` already exists (it really **should** be present in the specification already).

Yeah, sorry im in the process of updating the details. Will notify you when it's ready for another review,

**Comment by 6185541513** [comment]
@mantono now it's ready for review.

**Pull request merged**
