### PR TITLE
Add message event types

### PR DESCRIPTION
**Pull request by mantono**
Enabling brokers and banks to send messages and leave comments about an application. See MBB-11.

### CODE REVIEW

**Comment by Torbacka** [comment]
Maybe add a comment in the documentation that the event can only be sent in one direction. Else it looks nice.

**Comment by mantono** [comment]
All right, will do that.

**Comment by williamhogman** [comment]
Actually I think this overloads the meaning of the term "Message" in the specification perhaps "Notice" would be more apt

**Comment by mantono** [comment]
> Actually I think this overloads the meaning of the term "Message" in the specification perhaps "Notice" would be more apt

I do not think this is a concern. The term _message_ [is not widely used before this pull request](https://github.com/open-broker/specification/search?q=message&type=Code).

**Comment by mantono** [comment]
@williamhogman however, the term _bank_ is not used (except in the context of _bank accounts_) prior to this. Maybe BankMessage should be named something else to be more consistent? _ServiceProviderMessage_?

**Comment by mantono** [comment]
After further discussion we have come to the conclusion that this is not quite what we need. Closing PR.

**Pull request closed without merging**
