### PR TITLE
Adds message to sweden specification

### PR DESCRIPTION
**Pull request by Torbacka**
We need a more generic way of sending information from bank to the broker.

### CODE REVIEW

**Comment by zinob** [comment]
@mantono @Torbacka To be more precise than "somewhere" maybe it should be mentioned where the direction of other message types are listed? https://github.com/open-broker/specification/tree/master/se/PrivateUnsecuredLoan#events-from-service-provider-to-broker

**Comment by mantono** [comment]
> @mantono @Torbacka To be more precise than "somewhere" maybe it should be mentioned where the direction of other message types are listed? https://github.com/open-broker/specification/tree/master/se/PrivateUnsecuredLoan#events-from-service-provider-to-broker

Absolutely! I recall having such list in the docs, but didn't remember we had it for PrivateUnsecuredLoan SE.

**Comment by zinob** [comment]
.. on and @Torbacka had already added that to the file ,but i didnt see it..
Most other message types does not clearly specify the direction in the message it self.

**Comment by mantono** [comment]
> .. on and @Torbacka had already added that to the file ,but i didnt see it..
> Most other message types does not clearly specify the direction in the message deffinition it self.

Oh, you are right. I missed it too because I didn't see the full context. Shame on me! I think it could still be worth mentioning in the description of the event in the specification, but I would say that is up to @Torbacka to decide.

**Comment by Torbacka** [comment]
Have improved the description of the event. Will probably merge it during the day no one is against it.

**Pull request merged**
